---
abstract: 'Dynamic DNS update for Namecheap registered domains.'
author:
  - 'David Watson <dwatson@cpan.org>'
build_requires:
  Data::Dumper: 0
  Test::More: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-DDNS-Namecheap
requires:
  Carp: 0
  LWP::Simple: 0
  Moose: 0
  Mozilla::CA: 0
  perl: 5.010
resources:
  bugtracker: https://github.com/terminalfool/App-DDNS-Namecheap/issues
  repository: git://github.com/terminalfool/App-DDNS-Namecheap.git
version: 0.01
